packages:
  - '.'
  - 'docs'

# Needed for prettier to be able to use the plugin specified by @sanity/prettier-config
publicHoistPattern:
  - prettier-plugin-packagejson

allowBuilds:
  esbuild: false
