name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  test:
    timeout-minutes: 60
    name: Test (${{ matrix.os-version }} / node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os-version }}
    strategy:
      # we want to know if a test fails on a specific node version
      fail-fast: false
      matrix:
        os-version: [ubuntu-latest]
        node-version: [22, lts/*]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # ratchet:pnpm/action-setup@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: |
          node -v
          pnpm test
